### ISSUE TITLE
论文阅读侧边栏选择按钮随侧边栏隐藏

### ISSUE THREAD

**Issue by MikeWalrus** [LSX-s-Software/PaperPilotApp#29]
![Simulator Screenshot - Apple Vision Pro - 2023-11-15 at 21 08 39](https://github.com/LSX-s-Software/PaperPilotApp/assets/70618504/f0b637b3-0b58-46c0-859e-a78eb9a9774f)

侧边栏隐藏后无法复原。

**Comment by LSX-s-Software** [comment]
https://github.com/LSX-s-Software/PaperPilotApp/blob/06be3d1580ee9266578247114c95351b4fecc1fc/PaperPilot/Views/Reader/PaperReader.swift#L70C1-L76C7
这个条件编译设置了在**非iOS系统**上移除切换侧边栏的按钮，修改这个应该可以解决问题
